## Import Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.options.display.max_columns = None

## Import Data

In [3]:
train_input = pd.read_csv('loan_data_inputs_train.csv', index_col=0)
train_output = pd.read_csv('loan_data_targets_train.csv', index_col=0, header=None)
test_input = pd.read_csv('loan_data_inputs_test.csv', index_col=0)
test_output = pd.read_csv('loan_data_targets_test.csv', index_col=0, header=None)

In [4]:
train_input.shape, train_output.shape, test_input.shape, test_output.shape

((373028, 324), (373028, 1), (93257, 324), (93257, 1))

## Select Features

In [5]:
train_input_with_ref = train_input.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'delinq_2yrs:0',
'delinq_2yrs:1-3',
'delinq_2yrs:>=4',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'open_acc:0',
'open_acc:1-3',
'open_acc:4-12',
'open_acc:13-17',
'open_acc:18-22',
'open_acc:23-25',
'open_acc:26-30',
'open_acc:>=31',
'pub_rec:0-2',
'pub_rec:3-4',
'pub_rec:>=5',
'total_acc:<=27',
'total_acc:28-51',
'total_acc:>=52',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'total_rev_hi_lim:<=5K',
'total_rev_hi_lim:5K-10K',
'total_rev_hi_lim:10K-20K',
'total_rev_hi_lim:20K-30K',
'total_rev_hi_lim:30K-40K',
'total_rev_hi_lim:40K-55K',
'total_rev_hi_lim:55K-95K',
'total_rev_hi_lim:>95K',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86']]

In [6]:
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'delinq_2yrs:>=4',
'inq_last_6mths:>6',
'open_acc:0',
'pub_rec:0-2',
'total_acc:<=27',
'acc_now_delinq:0',
'total_rev_hi_lim:<=5K',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [7]:
train_input_with_ref.shape

(373028, 126)

In [8]:
X_train = train_input_with_ref.drop(ref_categories, axis=1)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [10]:
lr = LogisticRegression()

In [11]:
model = lr.fit(X_train, train_output)

/Users/osamaqureshi/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/osamaqureshi/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [12]:
lr.coef_

array([[ 1.11551267,  0.87811394,  0.68403489,  0.49615035,  0.32083117,
         0.13271166,  0.09128992,  0.10675717,  0.03730113,  0.05919601,
         0.06003572,  0.06260967,  0.07866972,  0.13625202,  0.10054942,
         0.18505749,  0.24097457,  0.2243762 ,  0.26301002,  0.32113179,
         0.52244894,  0.08814419, -0.0107055 ,  0.30436755,  0.20081869,
         0.21340198,  0.26651478,  0.05393763,  0.07929124,  0.10043074,
         0.12543437,  0.09063946,  0.0605655 ,  0.12322769,  1.07158386,
         0.87125938,  0.7709478 ,  0.57003045,  0.4085101 ,  0.16328568,
        -0.07248484,  0.88214577,  0.5548394 ,  0.30345789,  0.11139978,
         0.05571576,  0.03744298,  0.07847025,  0.11912794,  0.12471844,
         0.09019545,  0.04751855,  0.66665305,  0.52292063,  0.313541  ,
         0.31865647,  0.22228271,  0.19623771,  0.17983654,  0.17813204,
         0.20694344,  0.12031161,  0.12233471,  0.15780393, -0.02023297,
         0.02663503,  0.20069321,  0.04262727,  0.01160324,  0.01097499,
         0.02531066,  0.04689716,  0.07270552,  0.22412796, -0.07035768,
        -0.00221134,  0.09544198,  0.16422616,  0.24013203,  0.31387108,
         0.38936234,  0.40814275,  0.48533074,  0.57330153,  0.49990617,
         0.20463562,  0.33109296,  0.36010102,  0.30054183,  0.22455147,
         0.12671262,  0.11565942,  0.08149078,  0.04194772,  0.07245487,
         0.14091397,  0.1516888 ,  0.10383885,  0.3543856 ,  0.44489649,
         0.37861985,  0.54016528,  0.20590997,  0.27060984]])

In [13]:
lr.intercept_

array([-1.69853614])

In [14]:
feature_name = X_train.columns.values

In [15]:
summary_table = pd.DataFrame(columns=['Feature Names'], data=feature_name)

In [16]:
summary_table['Coefficients'] = np.transpose(lr.coef_)

In [17]:
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept', lr.intercept_[0]]

In [18]:
summary_table = summary_table.sort_index()

In [19]:
summary_table

                           Feature Names  Coefficients
0                              Intercept     -1.698536
1                                grade:A      1.115513
2                                grade:B      0.878114
3                                grade:C      0.684035
4                                grade:D      0.496150
5                                grade:E      0.320831
6                                grade:F      0.132712
7                     home_ownership:OWN      0.091290
8                home_ownership:MORTGAGE      0.106757
9                       addr_state:NM_VA      0.037301
10                         addr_state:NY      0.059196
11          addr_state:OK_TN_MO_LA_MD_NC      0.060036
12                         addr_state:CA      0.062610
13                addr_state:UT_KY_AZ_NJ      0.078670
14             addr_state:AR_MI_PA_OH_MN      0.136252
15             addr_state:RI_MA_DE_SD_IN      0.100549
16                   addr_state:GA_WA_OR      0.185057
17                      addr_state:WI_MT      0.240975
18                         addr_state:TX      0.224376
19                      addr_state:IL_CT      0.263010
20          addr_state:KS_SC_CO_VT_AK_MS      0.321132
21          addr_state:WV_NH_WY_DC_ME_ID      0.522449
22      verification_status:Not Verified      0.088144
23   verification_status:Source Verified     -0.010705
24                   purpose:credit_card      0.304368
25            purpose:debt_consolidation      0.200819
26            purpose:oth__med__vacation      0.213402
27   purpose:major_purch__car__home_impr      0.266515
28                 initial_list_status:w      0.053938
29                               term:36      0.079291
..                                   ...           ...
75                    annual_inc:20K-30K     -0.070358
76                    annual_inc:30K-40K     -0.002211
77                    annual_inc:40K-50K      0.095442
78                    annual_inc:50K-60K      0.164226
79                    annual_inc:60K-70K      0.240132
80                    annual_inc:70K-80K      0.313871
81                    annual_inc:80K-90K      0.389362
82                   annual_inc:90K-100K      0.408143
83                  annual_inc:100K-120K      0.485331
84                  annual_inc:120K-140K      0.573302
85                      annual_inc:>140K      0.499906
86                             dti:<=1.4      0.204636
87                           dti:1.4-3.5      0.331093
88                           dti:3.5-7.7      0.360101
89                          dti:7.7-10.5      0.300542
90                         dti:10.5-16.1      0.224551
91                         dti:16.1-20.3      0.126713
92                         dti:20.3-21.7      0.115659
93                         dti:21.7-22.4      0.081491
94                           dti:22.4-35      0.041948
95        mths_since_last_delinq:Missing      0.072455
96           mths_since_last_delinq:4-30      0.140914
97          mths_since_last_delinq:31-56      0.151689
98           mths_since_last_delinq:>=57      0.103839
99        mths_since_last_record:Missing      0.354386
100          mths_since_last_record:3-20      0.444896
101         mths_since_last_record:21-31      0.378620
102         mths_since_last_record:32-80      0.540165
103         mths_since_last_record:81-86      0.205910
104           mths_since_last_record:>86      0.270610

[105 rows x 2 columns]

In [20]:
from sklearn import linear_model
import scipy.stats as stat

class LogisticRegression_with_p_values:
    
    def __init__(self,*args,**kwargs):
        self.model = linear_model.LogisticRegression(*args,**kwargs)

    def fit(self,X,y):
        self.model.fit(X,y)
        denom = (2.0 * (1.0 + np.cosh(self.model.decision_function(X))))
        denom = np.tile(denom,(X.shape[1],1)).T
        F_ij = np.dot((X / denom).T,X)
        Cramer_Rao = np.linalg.inv(F_ij)
        sigma_estimates = np.sqrt(np.diagonal(Cramer_Rao))
        z_scores = self.model.coef_[0] / sigma_estimates
        p_values = [stat.norm.sf(abs(x)) * 2 for x in z_scores]
        self.coef_ = self.model.coef_
        self.intercept_ = self.model.intercept_
        self.p_values = p_values

In [21]:
reg = LogisticRegression_with_p_values()

In [22]:
model = reg.fit(X_train, train_output)

/Users/osamaqureshi/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/osamaqureshi/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [23]:
summary_table = pd.DataFrame(columns=['Feature Names'], data=feature_name)
summary_table['Coefficients'] = np.transpose(reg.coef_)
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

                           Feature Names  Coefficients
0                              Intercept     -1.698536
1                                grade:A      1.115513
2                                grade:B      0.878114
3                                grade:C      0.684035
4                                grade:D      0.496150
5                                grade:E      0.320831
6                                grade:F      0.132712
7                     home_ownership:OWN      0.091290
8                home_ownership:MORTGAGE      0.106757
9                       addr_state:NM_VA      0.037301
10                         addr_state:NY      0.059196
11          addr_state:OK_TN_MO_LA_MD_NC      0.060036
12                         addr_state:CA      0.062610
13                addr_state:UT_KY_AZ_NJ      0.078670
14             addr_state:AR_MI_PA_OH_MN      0.136252
15             addr_state:RI_MA_DE_SD_IN      0.100549
16                   addr_state:GA_WA_OR      0.185057
17                      addr_state:WI_MT      0.240975
18                         addr_state:TX      0.224376
19                      addr_state:IL_CT      0.263010
20          addr_state:KS_SC_CO_VT_AK_MS      0.321132
21          addr_state:WV_NH_WY_DC_ME_ID      0.522449
22      verification_status:Not Verified      0.088144
23   verification_status:Source Verified     -0.010705
24                   purpose:credit_card      0.304368
25            purpose:debt_consolidation      0.200819
26            purpose:oth__med__vacation      0.213402
27   purpose:major_purch__car__home_impr      0.266515
28                 initial_list_status:w      0.053938
29                               term:36      0.079291
..                                   ...           ...
75                    annual_inc:20K-30K     -0.070358
76                    annual_inc:30K-40K     -0.002211
77                    annual_inc:40K-50K      0.095442
78                    annual_inc:50K-60K      0.164226
79                    annual_inc:60K-70K      0.240132
80                    annual_inc:70K-80K      0.313871
81                    annual_inc:80K-90K      0.389362
82                   annual_inc:90K-100K      0.408143
83                  annual_inc:100K-120K      0.485331
84                  annual_inc:120K-140K      0.573302
85                      annual_inc:>140K      0.499906
86                             dti:<=1.4      0.204636
87                           dti:1.4-3.5      0.331093
88                           dti:3.5-7.7      0.360101
89                          dti:7.7-10.5      0.300542
90                         dti:10.5-16.1      0.224551
91                         dti:16.1-20.3      0.126713
92                         dti:20.3-21.7      0.115659
93                         dti:21.7-22.4      0.081491
94                           dti:22.4-35      0.041948
95        mths_since_last_delinq:Missing      0.072455
96           mths_since_last_delinq:4-30      0.140914
97          mths_since_last_delinq:31-56      0.151689
98           mths_since_last_delinq:>=57      0.103839
99        mths_since_last_record:Missing      0.354386
100          mths_since_last_record:3-20      0.444896
101         mths_since_last_record:21-31      0.378620
102         mths_since_last_record:32-80      0.540165
103         mths_since_last_record:81-86      0.205910
104           mths_since_last_record:>86      0.270610

[105 rows x 2 columns]

In [24]:
p_values = reg.p_values

In [25]:
p_values = np.append(np.nan, np.array(p_values))

In [26]:
summary_table['p_values'] = p_values
summary_table

                           Feature Names  Coefficients      p_values
0                              Intercept     -1.698536           NaN
1                                grade:A      1.115513  1.419576e-34
2                                grade:B      0.878114  1.079261e-46
3                                grade:C      0.684035  1.810640e-33
4                                grade:D      0.496150  3.305262e-20
5                                grade:E      0.320831  2.744690e-11
6                                grade:F      0.132712  8.227700e-03
7                     home_ownership:OWN      0.091290  6.085534e-06
8                home_ownership:MORTGAGE      0.106757  4.284168e-17
9                       addr_state:NM_VA      0.037301  2.447849e-01
10                         addr_state:NY      0.059196  1.481602e-02
11          addr_state:OK_TN_MO_LA_MD_NC      0.060036  9.696754e-03
12                         addr_state:CA      0.062610  3.210123e-03
13                addr_state:UT_KY_AZ_NJ      0.078670  1.622282e-03
14             addr_state:AR_MI_PA_OH_MN      0.136252  1.609430e-09
15             addr_state:RI_MA_DE_SD_IN      0.100549  7.659231e-04
16                   addr_state:GA_WA_OR      0.185057  4.320652e-12
17                      addr_state:WI_MT      0.240975  4.142370e-07
18                         addr_state:TX      0.224376  6.605075e-18
19                      addr_state:IL_CT      0.263010  2.531573e-19
20          addr_state:KS_SC_CO_VT_AK_MS      0.321132  2.482505e-25
21          addr_state:WV_NH_WY_DC_ME_ID      0.522449  9.950598e-23
22      verification_status:Not Verified      0.088144  2.073518e-09
23   verification_status:Source Verified     -0.010705  4.269280e-01
24                   purpose:credit_card      0.304368  1.035267e-26
25            purpose:debt_consolidation      0.200819  1.673831e-14
26            purpose:oth__med__vacation      0.213402  8.467898e-12
27   purpose:major_purch__car__home_impr      0.266515  1.987671e-17
28                 initial_list_status:w      0.053938  3.614913e-05
29                               term:36      0.079291  2.256637e-08
..                                   ...           ...           ...
75                    annual_inc:20K-30K     -0.070358  1.018166e-01
76                    annual_inc:30K-40K     -0.002211  9.575114e-01
77                    annual_inc:40K-50K      0.095442  2.161754e-02
78                    annual_inc:50K-60K      0.164226  9.723942e-05
79                    annual_inc:60K-70K      0.240132  2.615908e-08
80                    annual_inc:70K-80K      0.313871  1.048010e-12
81                    annual_inc:80K-90K      0.389362  2.103586e-17
82                   annual_inc:90K-100K      0.408143  8.231157e-18
83                  annual_inc:100K-120K      0.485331  8.347911e-25
84                  annual_inc:120K-140K      0.573302  7.106987e-27
85                      annual_inc:>140K      0.499906  6.975897e-24
86                             dti:<=1.4      0.204636  2.061733e-02
87                           dti:1.4-3.5      0.331093  9.675160e-06
88                           dti:3.5-7.7      0.360101  3.465370e-08
89                          dti:7.7-10.5      0.300542  3.401522e-06
90                         dti:10.5-16.1      0.224551  3.433395e-04
91                         dti:16.1-20.3      0.126713  4.324377e-02
92                         dti:20.3-21.7      0.115659  7.581461e-02
93                         dti:21.7-22.4      0.081491  2.372632e-01
94                           dti:22.4-35      0.041948  4.982307e-01
95        mths_since_last_delinq:Missing      0.072455  2.077759e-01
96           mths_since_last_delinq:4-30      0.140914  8.018869e-03
97          mths_since_last_delinq:31-56      0.151689  9.633814e-03
98           mths_since_last_delinq:>=57      0.103839  8.218659e-02
99        mths_since_last_record:Missing      0.354386  3.699899e-05
100          mths_since_last_record:3-20      0.444896  4.510974e-04
101         mths_since_last_record:21-31      0.378620  1.157857e-03
102         mths_since_last_record:32-80      0.540165  1.987930e-09
103         mths_since_last_record:81-86      0.205910  5.220517e-02
104           mths_since_last_record:>86      0.270610  2.259217e-03

[105 rows x 3 columns]

In [27]:
summary_table['p_values']

0               NaN
1      1.419576e-34
2      1.079261e-46
3      1.810640e-33
4      3.305262e-20
5      2.744690e-11
6      8.227700e-03
7      6.085534e-06
8      4.284168e-17
9      2.447849e-01
10     1.481602e-02
11     9.696754e-03
12     3.210123e-03
13     1.622282e-03
14     1.609430e-09
15     7.659231e-04
16     4.320652e-12
17     4.142370e-07
18     6.605075e-18
19     2.531573e-19
20     2.482505e-25
21     9.950598e-23
22     2.073518e-09
23     4.269280e-01
24     1.035267e-26
25     1.673831e-14
26     8.467898e-12
27     1.987671e-17
28     3.614913e-05
29     2.256637e-08
           ...
75     1.018166e-01
76     9.575114e-01
77     2.161754e-02
78     9.723942e-05
79     2.615908e-08
80     1.048010e-12
81     2.103586e-17
82     8.231157e-18
83     8.347911e-25
84     7.106987e-27
85     6.975897e-24
86     2.061733e-02
87     9.675160e-06
88     3.465370e-08
89     3.401522e-06
90     3.433395e-04
91     4.324377e-02
92     7.581461e-02
93     2.372632e-01
94     4.982307e-01
95     2.077759e-01
96     8.018869e-03
97     9.633814e-03
98     8.218659e-02
99     3.699899e-05
100    4.510974e-04
101    1.157857e-03
102    1.987930e-09
103    5.220517e-02
104    2.259217e-03
Name: p_values, Length: 105, dtype: float64

In [38]:
inputs_train_with_ref_cat = X_train.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86']]

ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

/Users/osamaqureshi/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1494: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

In [39]:
X_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)
X_train.head()

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:NM_VA,addr_state:NY,addr_state:OK_TN_MO_LA_MD_NC,addr_state:CA,addr_state:UT_KY_AZ_NJ,addr_state:AR_MI_PA_OH_MN,addr_state:RI_MA_DE_SD_IN,addr_state:GA_WA_OR,addr_state:WI_MT,addr_state:TX,addr_state:IL_CT,addr_state:KS_SC_CO_VT_AK_MS,addr_state:WV_NH_WY_DC_ME_ID,verification_status:Not Verified,verification_status:Source Verified,purpose:credit_card,purpose:debt_consolidation,purpose:oth__med__vacation,purpose:major_purch__car__home_impr,initial_list_status:w,term:36,emp_length:1,emp_length:2-4,emp_length:5-6,emp_length:7-9,emp_length:10,mths_since_issue_d:<38,mths_since_issue_d:38-39,mths_since_issue_d:40-41,mths_since_issue_d:42-48,mths_since_issue_d:49-52,mths_since_issue_d:53-64,mths_since_issue_d:65-84,int_rate:<9.548,int_rate:9.548-12.025,int_rate:12.025-15.74,int_rate:15.74-20.281,mths_since_earliest_cr_line:141-164,mths_since_earliest_cr_line:165-247,mths_since_earliest_cr_line:248-270,mths_since_earliest_cr_line:271-352,mths_since_earliest_cr_line:>352,inq_last_6mths:0,inq_last_6mths:1-2,inq_last_6mths:3-6,acc_now_delinq:>=1,annual_inc:20K-30K,annual_inc:30K-40K,annual_inc:40K-50K,annual_inc:50K-60K,annual_inc:60K-70K,annual_inc:70K-80K,annual_inc:80K-90K,annual_inc:90K-100K,annual_inc:100K-120K,annual_inc:120K-140K,annual_inc:>140K,dti:<=1.4,dti:1.4-3.5,dti:3.5-7.7,dti:7.7-10.5,dti:10.5-16.1,dti:16.1-20.3,dti:20.3-21.7,dti:21.7-22.4,dti:22.4-35,mths_since_last_delinq:Missing,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:Missing,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
427211,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0
206088,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0
136020,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0
412305,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0
36159,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0

In [40]:
reg2 = LogisticRegression_with_p_values()
reg2.fit(X_train, train_output)

/Users/osamaqureshi/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/osamaqureshi/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [41]:
feature_name = X_train.columns.values 
summary_table = pd.DataFrame(columns=['Feature Names'], data=feature_name)
summary_table['Coefficients'] = np.transpose(reg2.coef_)
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept', reg2.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

                          Feature Names  Coefficients
0                             Intercept     -1.385294
1                               grade:A      1.121514
2                               grade:B      0.881471
3                               grade:C      0.687844
4                               grade:D      0.500462
5                               grade:E      0.325080
6                               grade:F      0.137043
7                    home_ownership:OWN      0.093503
8               home_ownership:MORTGAGE      0.106010
9                      addr_state:NM_VA      0.037051
10                        addr_state:NY      0.057062
11         addr_state:OK_TN_MO_LA_MD_NC      0.059632
12                        addr_state:CA      0.063600
13               addr_state:UT_KY_AZ_NJ      0.078478
14            addr_state:AR_MI_PA_OH_MN      0.135478
15            addr_state:RI_MA_DE_SD_IN      0.100867
16                  addr_state:GA_WA_OR      0.185780
17                     addr_state:WI_MT      0.240484
18                        addr_state:TX      0.222366
19                     addr_state:IL_CT      0.261841
20         addr_state:KS_SC_CO_VT_AK_MS      0.320732
21         addr_state:WV_NH_WY_DC_ME_ID      0.522251
22     verification_status:Not Verified      0.085882
23  verification_status:Source Verified     -0.010933
24                  purpose:credit_card      0.301419
25           purpose:debt_consolidation      0.197791
26           purpose:oth__med__vacation      0.213345
27  purpose:major_purch__car__home_impr      0.265437
28                initial_list_status:w      0.054415
29                              term:36      0.078516
..                                  ...           ...
55                   annual_inc:20K-30K     -0.076556
56                   annual_inc:30K-40K     -0.013044
57                   annual_inc:40K-50K      0.081671
58                   annual_inc:50K-60K      0.148743
59                   annual_inc:60K-70K      0.224316
60                   annual_inc:70K-80K      0.298261
61                   annual_inc:80K-90K      0.374170
62                  annual_inc:90K-100K      0.393905
63                 annual_inc:100K-120K      0.472347
64                 annual_inc:120K-140K      0.563181
65                     annual_inc:>140K      0.499151
66                            dti:<=1.4      0.245676
67                          dti:1.4-3.5      0.360989
68                          dti:3.5-7.7      0.379458
69                         dti:7.7-10.5      0.314803
70                        dti:10.5-16.1      0.235964
71                        dti:16.1-20.3      0.134777
72                        dti:20.3-21.7      0.122523
73                        dti:21.7-22.4      0.087610
74                          dti:22.4-35      0.045878
75       mths_since_last_delinq:Missing      0.116776
76          mths_since_last_delinq:4-30      0.143820
77         mths_since_last_delinq:31-56      0.189960
78          mths_since_last_delinq:>=57      0.142876
79       mths_since_last_record:Missing      0.324790
80          mths_since_last_record:3-20      0.435892
81         mths_since_last_record:21-31      0.357036
82         mths_since_last_record:32-80      0.509891
83         mths_since_last_record:81-86      0.171721
84           mths_since_last_record:>86      0.237583

[85 rows x 2 columns]

In [42]:
p_values = reg2.p_values
p_values = np.append(np.nan, np.array(p_values))
summary_table['p_values'] = p_values
summary_table

                          Feature Names  Coefficients      p_values
0                             Intercept     -1.385294           NaN
1                               grade:A      1.121514  4.756366e-35
2                               grade:B      0.881471  2.177630e-47
3                               grade:C      0.687844  3.277680e-34
4                               grade:D      0.500462  6.949147e-21
5                               grade:E      0.325080  5.881953e-12
6                               grade:F      0.137043  5.230809e-03
7                    home_ownership:OWN      0.093503  3.463745e-06
8               home_ownership:MORTGAGE      0.106010  5.187309e-17
9                      addr_state:NM_VA      0.037051  2.473140e-01
10                        addr_state:NY      0.057062  1.846733e-02
11         addr_state:OK_TN_MO_LA_MD_NC      0.059632  9.994597e-03
12                        addr_state:CA      0.063600  2.694031e-03
13               addr_state:UT_KY_AZ_NJ      0.078478  1.630561e-03
14            addr_state:AR_MI_PA_OH_MN      0.135478  1.793690e-09
15            addr_state:RI_MA_DE_SD_IN      0.100867  7.237999e-04
16                  addr_state:GA_WA_OR      0.185780  3.245574e-12
17                     addr_state:WI_MT      0.240484  4.261354e-07
18                        addr_state:TX      0.222366  1.129114e-17
19                     addr_state:IL_CT      0.261841  3.090208e-19
20         addr_state:KS_SC_CO_VT_AK_MS      0.320732  2.443368e-25
21         addr_state:WV_NH_WY_DC_ME_ID      0.522251  9.651425e-23
22     verification_status:Not Verified      0.085882  4.086130e-09
23  verification_status:Source Verified     -0.010933  4.156334e-01
24                  purpose:credit_card      0.301419  1.491613e-26
25           purpose:debt_consolidation      0.197791  2.745061e-14
26           purpose:oth__med__vacation      0.213345  6.914981e-12
27  purpose:major_purch__car__home_impr      0.265437  1.847676e-17
28                initial_list_status:w      0.054415  3.069297e-05
29                              term:36      0.078516  1.948287e-08
..                                  ...           ...           ...
55                   annual_inc:20K-30K     -0.076556  6.881808e-02
56                   annual_inc:30K-40K     -0.013044  7.469506e-01
57                   annual_inc:40K-50K      0.081671  4.306732e-02
58                   annual_inc:50K-60K      0.148743  2.753500e-04
59                   annual_inc:60K-70K      0.224316  8.151080e-08
60                   annual_inc:70K-80K      0.298261  2.712305e-12
61                   annual_inc:80K-90K      0.374170  3.699227e-17
62                  annual_inc:90K-100K      0.393905  1.108480e-17
63                 annual_inc:100K-120K      0.472347  3.992683e-25
64                 annual_inc:120K-140K      0.563181  1.896839e-27
65                     annual_inc:>140K      0.499151  8.333760e-26
66                            dti:<=1.4      0.245676  3.213373e-03
67                          dti:1.4-3.5      0.360989  2.482960e-07
68                          dti:3.5-7.7      0.379458  3.103431e-10
69                         dti:7.7-10.5      0.314803  1.492684e-07
70                        dti:10.5-16.1      0.235964  4.607457e-05
71                        dti:16.1-20.3      0.134777  2.012853e-02
72                        dti:20.3-21.7      0.122523  4.354278e-02
73                        dti:21.7-22.4      0.087610  1.762147e-01
74                          dti:22.4-35      0.045878  4.234845e-01
75       mths_since_last_delinq:Missing      0.116776  2.513791e-02
76          mths_since_last_delinq:4-30      0.143820  6.336764e-03
77         mths_since_last_delinq:31-56      0.189960  3.710667e-04
78          mths_since_last_delinq:>=57      0.142876  8.923252e-03
79       mths_since_last_record:Missing      0.324790  6.405248e-05
80          mths_since_last_record:3-20      0.435892  3.759616e-04
81         mths_since_last_record:21-31      0.357036  1.510556e-03
82         mths_since_last_record:32-80      0.509891  2.359380e-09
83         mths_since_last_record:81-86      0.171721  9.312120e-02
84           mths_since_last_record:>86      0.237583  4.742365e-03

[85 rows x 3 columns]

In [43]:
inputs_test_with_ref_cat = test_input.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86']]

ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [44]:
X_test = inputs_test_with_ref_cat.drop(ref_categories, axis = 1)
X_test.head()

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:NM_VA,addr_state:NY,addr_state:OK_TN_MO_LA_MD_NC,addr_state:CA,addr_state:UT_KY_AZ_NJ,addr_state:AR_MI_PA_OH_MN,addr_state:RI_MA_DE_SD_IN,addr_state:GA_WA_OR,addr_state:WI_MT,addr_state:TX,addr_state:IL_CT,addr_state:KS_SC_CO_VT_AK_MS,addr_state:WV_NH_WY_DC_ME_ID,verification_status:Not Verified,verification_status:Source Verified,purpose:credit_card,purpose:debt_consolidation,purpose:oth__med__vacation,purpose:major_purch__car__home_impr,initial_list_status:w,term:36,emp_length:1,emp_length:2-4,emp_length:5-6,emp_length:7-9,emp_length:10,mths_since_issue_d:<38,mths_since_issue_d:38-39,mths_since_issue_d:40-41,mths_since_issue_d:42-48,mths_since_issue_d:49-52,mths_since_issue_d:53-64,mths_since_issue_d:65-84,int_rate:<9.548,int_rate:9.548-12.025,int_rate:12.025-15.74,int_rate:15.74-20.281,mths_since_earliest_cr_line:141-164,mths_since_earliest_cr_line:165-247,mths_since_earliest_cr_line:248-270,mths_since_earliest_cr_line:271-352,mths_since_earliest_cr_line:>352,inq_last_6mths:0,inq_last_6mths:1-2,inq_last_6mths:3-6,acc_now_delinq:>=1,annual_inc:20K-30K,annual_inc:30K-40K,annual_inc:40K-50K,annual_inc:50K-60K,annual_inc:60K-70K,annual_inc:70K-80K,annual_inc:80K-90K,annual_inc:90K-100K,annual_inc:100K-120K,annual_inc:120K-140K,annual_inc:>140K,dti:<=1.4,dti:1.4-3.5,dti:3.5-7.7,dti:7.7-10.5,dti:10.5-16.1,dti:16.1-20.3,dti:20.3-21.7,dti:21.7-22.4,dti:22.4-35,mths_since_last_delinq:Missing,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:Missing,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
362514,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0
288564,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0
213591,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0
263083,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0
165001,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0

In [45]:
y_predicted = reg2.model.predict(X_test)

In [46]:
y_predicted

array([1, 1, 1, ..., 1, 1, 1])

In [47]:
y_predicted.shape, y_predicted.sum()

((93257,), 93245)

In [49]:
93257-93245

12

In [50]:
y_predicted_prob = reg2.model.predict_proba(X_test)

In [53]:
y_predicted_prob.shape

(93257, 2)

In [55]:
y_predicted_prob = y_predicted_prob[:,1]

In [56]:
test_output_temp = test_output
test_output_temp.reset_index(drop=True, inplace=True)

In [57]:
test_output_temp

       1
0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      0
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     0
21     0
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
...   ..
93227  1
93228  1
93229  1
93230  1
93231  1
93232  1
93233  0
93234  1
93235  1
93236  1
93237  0
93238  1
93239  1
93240  1
93241  1
93242  1
93243  1
93244  1
93245  1
93246  1
93247  1
93248  1
93249  1
93250  1
93251  1
93252  1
93253  1
93254  0
93255  1
93256  1

[93257 rows x 1 columns]

In [59]:
df_prob = pd.concat([test_output_temp, pd.DataFrame(y_predicted_prob)],axis=1)
df_prob.head()

   1         0
0  1  0.924173
1  1  0.848553
2  1  0.885601
3  1  0.940579
4  1  0.968703

In [60]:
df_prob.shape

(93257, 2)

In [61]:
df_prob.columns = ['test_outputs','y_predicted_probability']
df_prob.head()

   test_outputs  y_predicted_probability
0             1                 0.924173
1             1                 0.848553
2             1                 0.885601
3             1                 0.940579
4             1                 0.968703

In [62]:
df_prob.index = test_output_temp.index

## Accuracy and AUC

In [63]:
tr = 0.5
df_prob['y_test'] = np.where(df_prob['test_outputs'] > tr, 1, 0)
df_prob.head()

   test_outputs  y_predicted_probability  y_test
0             1                 0.924173       1
1             1                 0.848553       1
2             1                 0.885601       1
3             1                 0.940579       1
4             1                 0.968703       1

In [68]:
pd.crosstab(df_prob['test_outputs'], df_prob['y_test'], 
            rownames=['Actuals'], colnames=['Predicted'])

Predicted      0      1
Actuals
0          10190      0
1              0  83067